[scene.market]
background = "/example_game/assets/market.bmp"
name = "熱鬧市場"

[scene.castle]
background = "/example_game/assets/castle.bmp"
name = "古老城堡"

[scene.forest]
background = "/example_game/assets/forest.bmp"
name = "幽深森林"

[scene.cave]
background = "/example_game/assets/cave.bmp"
name = "神秘洞窟"

[character.knight]
affinity = 50
avatar = "/example_game/assets/knight_avatar.bmp"
name = "騎士阿勇"
tachie = "/example_game/assets/knight_tachie.bmp"

[character.merchant]
affinity = 50
avatar = "/example_game/assets/merchant_avatar.bmp"
name = "商人"
tachie = "/example_game/assets/merchant_tachie.bmp"

[character.witch]
affinity = 50
avatar = "/example_game/assets/witch_avatar.bmp"
name = "女巫"
tachie = "/example_game/assets/witch_tachie.bmp"

[character.guard]
affinity = 50
avatar = "/example_game/assets/guard_avatar.bmp"
name = "城堡守衛"
tachie = "/example_game/assets/guard_tachie.bmp"

[item.sword]
icon = "/example_game/assets/sword_icon.bmp"
name = "魔法劍"

[item.potion]
icon = "/example_game/assets/potion_icon.bmp"
name = "治療藥水"

[item.scroll]
icon = "/example_game/assets/scroll_icon.bmp"
name = "古卷軸"

[player]
inventory = ["sword", "potion", "scroll"]
role = "knight"

[event.start]
dialogue = "intro"
scene = "market"

[dialogue.intro]
character = "knight"
text = "今天是個充滿希望的日子，我需要準備好迎接挑戰。"
[[dialogue.intro.options]]
effect = "+10"
next = "meet_merchant"
text = "前往市場準備裝備。"

[dialogue.meet_merchant]
character = "merchant"
item = "sword"
text = "勇敢的騎士，這是你需要的魔法劍。"
[[dialogue.meet_merchant.options]]
effect = "+5"
event = "castle_entry"
text = "謝謝你，商人。"

[event.castle_entry]
dialogue = "castle_encounter"
scene = "castle"

[dialogue.castle_encounter]
character = "guard"
text = "騎士，這座城堡危險重重，你確定要進去嗎？"
[[dialogue.castle_encounter.options]]
effect = "+3"
next = "inside_castle"
text = "是的，我必須找到答案。"
[[dialogue.castle_encounter.options]]
effect = "+2"
event = "explore_forest"
text = "也許我應該先在森林裡尋找線索。"

[dialogue.inside_castle]
character = "knight"
text = "城堡內部比我想像的還要陰森。"
[[dialogue.inside_castle.options]]
effect = "+7"
event = "meet_witch"
text = "繼續探索，尋找女巫。"
[[dialogue.inside_castle.options]]
effect = "+5"
next = "scroll_clue"
text = "找到一卷古老的卷軸。"

[dialogue.scroll_clue]
character = "knight"
item = "scroll"
text = "這卷軸上記載了神秘的咒語，也許能幫助我。"
[[dialogue.scroll_clue.options]]
effect = "+4"
event = "meet_witch"
text = "去見女巫。"
[[dialogue.scroll_clue.options]]
effect = "+3"
event = "forest_cave"
text = "探索城堡後的洞窟。"

[event.explore_forest]
dialogue = "forest_path"
scene = "forest"

[dialogue.forest_path]
character = "knight"
text = "森林中充滿了危險和秘密。"
[[dialogue.forest_path.options]]
effect = "+6"
next = "potion_discovery"
text = "找到一瓶治療藥水。"
[[dialogue.forest_path.options]]
effect = "+5"
event = "forest_cave"
text = "發現了一個洞窟入口。"

[dialogue.potion_discovery]
character = "knight"
item = "potion"
text = "這瓶藥水或許能在緊急時救我一命。"
[[dialogue.potion_discovery.options]]
effect = "+4"
event = "forest_cave"
text = "前往洞窟。"
[[dialogue.potion_discovery.options]]
effect = "+3"
event = "return_castle"
text = "回到城堡探索。"

[event.return_castle]
dialogue = "back_to_castle"
scene = "castle"

[dialogue.back_to_castle]
character = "knight"
text = "回到城堡，希望能找到更多線索。"
[[dialogue.back_to_castle.options]]
effect = "+4"
next = "inside_castle"
text = "繼續探索城堡。"

[event.forest_cave]
dialogue = "inside_cave"
scene = "cave"

[dialogue.inside_cave]
character = "knight"
text = "洞窟裡陰暗潮濕，但似乎有重要的線索。"
[[dialogue.inside_cave.options]]
effect = "+7"
next = "witch_confrontation"
text = "發現女巫的藏身處。"
[[dialogue.inside_cave.options]]
effect = "+5"
next = "treasure_discovery"
text = "找到一間寶藏室。"

[dialogue.treasure_discovery]
character = "knight"
text = "這裡堆滿了金銀珠寶，卻隱藏著更大的秘密。"
[[dialogue.treasure_discovery.options]]
effect = "+6"
next = "witch_confrontation"
text = "尋找女巫。"
[[dialogue.treasure_discovery.options]]
effect = "+5"
event = "exit_cave"
text = "離開洞窟。"

[event.exit_cave]
dialogue = "leave_cave"
scene = "forest"

[dialogue.leave_cave]
character = "knight"
text = "我已經探索完洞窟，該回到城堡了。"
[[dialogue.leave_cave.options]]
effect = "+5"
event = "return_castle"
text = "回到城堡。"

[dialogue.witch_confrontation]
character = "witch"
text = "年輕的騎士，你來到這裡有何貴幹？"
[[dialogue.witch_confrontation.options]]
effect = "+4"
next = "battle"
text = "我來尋找真相，女巫。"
[[dialogue.witch_confrontation.options]]
effect = "+5"
next = "negotiate"
text = "或許我們可以達成協議。"

[dialogue.battle]
character = "knight"
text = "我不會退縮，準備戰鬥！"
[[dialogue.battle.options]]
effect = "+8"
event = "good_ending"
text = "擊敗女巫，解開城堡的詛咒。"
[[dialogue.battle.options]]
effect = "-10"
event = "bad_ending"
text = "被女巫擊敗，陷入黑暗。"
[[dialogue.battle.options]]
effect = "+5"
event = "neutral_ending"
text = "與女巫達成協議，共同探索真相。"

[dialogue.negotiate]
character = "witch"
text = "你有勇氣，我願意聽你說。"
[[dialogue.negotiate.options]]
effect = "+6"
event = "neutral_ending"
text = "提出協議，共同探索真相。"
[[dialogue.negotiate.options]]
effect = "-5"
event = "bad_ending"
text = "女巫反悔，戰鬥爆發。"

[event.good_ending]
dialogue = "victory"
scene = "market"

[dialogue.victory]
character = "knight"
text = "城堡的詛咒已經解除，和平終於回到了這片土地。"
[[dialogue.victory.options]]
effect = "+10"
event = "end"
text = "回到市場，與朋友慶祝。"

[event.bad_ending]
dialogue = "defeat"
scene = "forest"

[dialogue.defeat]
character = "witch"
text = "你太天真了，騎士，這片土地永遠屬於我！"
[[dialogue.defeat.options]]
effect = "-10"
event = "end"
text = "黑暗籠罩了一切。"

[event.neutral_ending]
dialogue = "agreement"
scene = "forest"

[dialogue.agreement]
character = "knight"
text = "我們達成協議，共同揭開了真相，和平來之不易。"
[[dialogue.agreement.options]]
effect = "+5"
event = "end"
text = "回到市場，思考未來。"

[event.end]
dialogue = "farewell"
scene = "market"

[dialogue.farewell]
character = "knight"
text = "這次的冒險讓我成長許多，我期待著下一次的挑戰。"
