[scene.market]
background = "/example_game/assets/market.bmp"
name = "Bustling Market"

[scene.castle]
background = "/example_game/assets/castle.bmp"
name = "Ancient Castle"

[scene.forest]
background = "/example_game/assets/forest.bmp"
name = "Deep Forest"

[scene.cave]
background = "/example_game/assets/cave.bmp"
name = "Mysterious Cave"

[character.knight]
affinity = 50
avatar = "/example_game/assets/knight_avatar.bmp"
name = "Knight A-Yong"
tachie = "/example_game/assets/knight_tachie.bmp"

[character.merchant]
affinity = 50
avatar = "/example_game/assets/merchant_avatar.bmp"
name = "Merchant"
tachie = "/example_game/assets/merchant_tachie.bmp"

[character.witch]
affinity = 50
avatar = "/example_game/assets/witch_avatar.bmp"
name = "Witch"
tachie = "/example_game/assets/witch_tachie.bmp"

[character.guard]
affinity = 50
avatar = "/example_game/assets/guard_avatar.bmp"
name = "Castle Guard"
tachie = "/example_game/assets/guard_tachie.bmp"

[item.sword]
icon = "/example_game/assets/sword_icon.bmp"
name = "Magic Sword"

[item.potion]
icon = "/example_game/assets/potion_icon.bmp"
name = "Healing Potion"

[item.scroll]
icon = "/example_game/assets/scroll_icon.bmp"
name = "Ancient Scroll"

[player]
inventory = ["sword", "potion", "scroll"]
role = "knight"

[event.start]
dialogue = "intro"
scene = "market"

[dialogue.intro]
character = "knight"
text = "Today is a hopeful day, I need to prepare for the challenges ahead."
[[dialogue.intro.options]]
effect = "+10"
next = "meet_merchant"
text = "Go to the market to prepare equipment."

[dialogue.meet_merchant]
character = "merchant"
item = "sword"
text = "Brave knight, this is the magic sword you need."
[[dialogue.meet_merchant.options]]
effect = "+5"
event = "castle_entry"
text = "Thank you, merchant."

[event.castle_entry]
dialogue = "castle_encounter"
scene = "castle"

[dialogue.castle_encounter]
character = "guard"
text = "Knight, this castle is full of dangers, are you sure you want to enter?"
[[dialogue.castle_encounter.options]]
effect = "+3"
next = "inside_castle"
text = "Yes, I must find the answer."
[[dialogue.castle_encounter.options]]
effect = "+2"
event = "explore_forest"
text = "Maybe I should search for clues in the forest first."

[dialogue.inside_castle]
character = "knight"
text = "The inside of the castle is gloomier than I imagined."
[[dialogue.inside_castle.options]]
effect = "+7"
event = "meet_witch"
text = "Continue exploring, looking for the witch."
[[dialogue.inside_castle.options]]
effect = "+5"
next = "scroll_clue"
text = "Found an ancient scroll."

[dialogue.scroll_clue]
character = "knight"
item = "scroll"
text = "This scroll records mysterious spells, maybe it can help me."
[[dialogue.scroll_clue.options]]
effect = "+4"
event = "meet_witch"
text = "Go to see the witch."
[[dialogue.scroll_clue.options]]
effect = "+3"
event = "forest_cave"
text = "Explore the cave behind the castle."

[event.explore_forest]
dialogue = "forest_path"
scene = "forest"

[dialogue.forest_path]
character = "knight"
text = "The forest is full of dangers and secrets."
[[dialogue.forest_path.options]]
effect = "+6"
next = "potion_discovery"
text = "Found a healing potion."
[[dialogue.forest_path.options]]
effect = "+5"
event = "forest_cave"
text = "Discovered a cave entrance."

[dialogue.potion_discovery]
character = "knight"
item = "potion"
text = "This potion might save my life in an emergency."
[[dialogue.potion_discovery.options]]
effect = "+4"
event = "forest_cave"
text = "Head to the cave."
[[dialogue.potion_discovery.options]]
effect = "+3"
event = "return_castle"
text = "Return to the castle to explore."

[event.return_castle]
dialogue = "back_to_castle"
scene = "castle"

[dialogue.back_to_castle]
character = "knight"
text = "Back at the castle, hoping to find more clues."
[[dialogue.back_to_castle.options]]
effect = "+4"
next = "inside_castle"
text = "Continue exploring the castle."

[event.forest_cave]
dialogue = "inside_cave"
scene = "cave"

[dialogue.inside_cave]
character = "knight"
text = "The cave is dark and damp, but seems to hold important clues."
[[dialogue.inside_cave.options]]
effect = "+7"
next = "witch_confrontation"
text = "Found the witch's hiding place."
[[dialogue.inside_cave.options]]
effect = "+5"
next = "treasure_discovery"
text = "Found a treasure room."

[dialogue.treasure_discovery]
character = "knight"
text = "This place is full of gold and jewels, but hides an even greater secret."
[[dialogue.treasure_discovery.options]]
effect = "+6"
next = "witch_confrontation"
text = "Search for the witch."
[[dialogue.treasure_discovery.options]]
effect = "+5"
event = "exit_cave"
text = "Leave the cave."

[event.exit_cave]
dialogue = "leave_cave"
scene = "forest"

[dialogue.leave_cave]
character = "knight"
text = "I've explored the cave, now I should return to the castle."
[[dialogue.leave_cave.options]]
effect = "+5"
event = "return_castle"
text = "Return to the castle."

[event.meet_witch]
dialogue = "witch_confrontation"
scene = "forest"

[dialogue.witch_confrontation]
character = "witch"
text = "Young knight, why have you come here?"
[[dialogue.witch_confrontation.options]]
effect = "+4"
next = "battle"
text = "I seek the truth, witch."
[[dialogue.witch_confrontation.options]]
effect = "+5"
next = "negotiate"
text = "Perhaps we can come to an agreement."

[dialogue.battle]
character = "knight"
text = "I will not back down, prepare for battle!"
[[dialogue.battle.options]]
effect = "+8"
event = "good_ending"
text = "Defeat the witch and lift the castle's curse."
[[dialogue.battle.options]]
effect = "-10"
event = "bad_ending"
text = "Defeated by the witch, engulfed in darkness."
[[dialogue.battle.options]]
effect = "+5"
event = "neutral_ending"
text = "Make an agreement with the witch, uncover the truth together."

[dialogue.negotiate]
character = "witch"
text = "You have courage, I will listen to you."
[[dialogue.negotiate.options]]
effect = "+6"
event = "neutral_ending"
text = "Propose an agreement, uncover the truth together."
[[dialogue.negotiate.options]]
effect = "-5"
event = "bad_ending"
text = "The witch goes back on her word, a fight ensues."

[event.good_ending]
dialogue = "victory"
scene = "market"

[dialogue.victory]
character = "knight"
text = "The castle's curse is lifted, peace has finally returned to this land."
[[dialogue.victory.options]]
effect = "+10"
text = "Return to the market to celebrate with friends."

[event.bad_ending]
dialogue = "defeat"
scene = "forest"

[dialogue.defeat]
character = "witch"
text = "You are too naive, knight. This land will always belong to me!"
[[dialogue.defeat.options]]
effect = "-10"
text = "Darkness enveloped everything..."

[event.neutral_ending]
dialogue = "agreement"
scene = "forest"

[dialogue.agreement]
character = "knight"
text = "We reached an agreement, uncovering the truth together. Peace is hard-won."
[[dialogue.agreement.options]]
effect = "+5"
event = "end"
text = "Return to the market, contemplating the future."

[event.end]
dialogue = "farewell"
scene = "market"

[dialogue.farewell]
character = "knight"
text = "This adventure has taught me much, I look forward to the next challenge."
